INSERT INTO operations."tipo_movilidad" (codigo, nombre) VALUES
('PA', 'Pasatía'),
('MA', 'Maestria'),
('CUCO', 'Curso corto'),
('ASAV', 'Asistencia a eventos'),
('MI', 'Misión'),
('DO', 'Doctorado'),
('PODO', 'Posdoctorado'),
('GECO', 'Gestión de convenio'),
('PRVI', 'Profesor visitante'),
('ESIN', 'Estancia investigava'),
('AUES', 'Aula espejo'),
('MA2', 'Maestria'),
('SEINV', 'Semillero de investigación'),
('DO2', 'Doctorado'),
('ES', 'Especializacion'),
('CUESP', 'Curso español'),
('ROMP', 'Rotacion medica'),
('SEINT', 'Semestre intercambio'),
('DOTI', 'Doble titulación'),
('VO', 'Voluntareado'),
('SE', 'Semillero'),
('PRPR', 'Practica profesional');